INSERT INTO suppliers (supplier_id, company_name, website, location, nature_of_business, manufacturing_processes)
VALUES
(1, 'Alpha Manufacturing', 'www.alpha.com', 'New York', 'small_scale', 'moulding'),
(2, 'Beta Industries', 'www.beta.com', 'Los Angeles', 'medium_scale', '3d_printing'),
(3, 'Gamma Tech', 'www.gamma.com', 'Chicago', 'large_scale', 'casting'),
(4, 'Delta Manufacturing', 'www.delta.com', 'Houston', 'small_scale', 'coating'),
(5, 'Epsilon Works', 'www.epsilon.com', 'Phoenix', 'medium_scale', 'moulding'),
(6, 'Zeta Manufacturing', 'www.zeta.com', 'Philadelphia', 'large_scale', '3d_printing'),
(7, 'Eta Solutions', 'www.eta.com', 'San Antonio', 'small_scale', 'casting'),
(8, 'Theta Fabricators', 'www.theta.com', 'San Diego', 'medium_scale', 'coating'),
(9, 'Iota Industries', 'www.iota.com', 'Dallas', 'large_scale', 'moulding'),
(10, 'Kappa Manufacturing', 'www.kappa.com', 'San Jose', 'small_scale', '3d_printing'),
(11, 'Lambda Enterprises', 'www.lambda.com', 'Austin', 'medium_scale', 'casting'),
(12, 'Mu Technologies', 'www.mu.com', 'Jacksonville', 'large_scale', 'coating'),
(13, 'Nu Manufacturing', 'www.nu.com', 'Fort Worth', 'small_scale', 'moulding'),
(14, 'Xi Works', 'www.xi.com', 'Columbus', 'medium_scale', '3d_printing'),
(15, 'Omicron Industries', 'www.omicron.com', 'Charlotte', 'large_scale', 'casting'),
(16, 'Pi Tech', 'www.pi.com', 'San Francisco', 'small_scale', 'coating'),
(17, 'Rho Manufacturing', 'www.rho.com', 'Indianapolis', 'medium_scale', 'moulding'),
(18, 'Sigma Solutions', 'www.sigma.com', 'Seattle', 'large_scale', '3d_printing'),
(19, 'Tau Fabricators', 'www.tau.com', 'Denver', 'small_scale', 'casting'),
(20, 'Upsilon Industries', 'www.upsilon.com', 'Washington', 'medium_scale', 'coating'),
(21, 'Phi Manufacturing', 'www.phi.com', 'Boston', 'large_scale', 'moulding'),
(22, 'Chi Enterprises', 'www.chi.com', 'El Paso', 'small_scale', '3d_printing'),
(23, 'Psi Technologies', 'www.psi.com', 'Nashville', 'medium_scale', 'casting'),
(24, 'Omega Manufacturing', 'www.omega.com', 'Detroit', 'large_scale', 'coating'),
(25, 'Alpha Beta Works', 'www.alphabeta.com', 'Memphis', 'small_scale', 'moulding'),
(26, 'Beta Gamma Manufacturing', 'www.betagamma.com', 'Portland', 'medium_scale', '3d_printing'),
(27, 'Gamma Delta Industries', 'www.gammadelta.com', 'Oklahoma City', 'large_scale', 'casting'),
(28, 'Delta Epsilon Tech', 'www.deltaepsilon.com', 'Las Vegas', 'small_scale', 'coating'),
(29, 'Epsilon Zeta Solutions', 'www.epsilonzeta.com', 'Louisville', 'medium_scale', 'moulding'),
(30, 'Zeta Eta Fabricators', 'www.zetaeta.com', 'Baltimore', 'large_scale', '3d_printing'),
(31, 'Eta Theta Manufacturing', 'www.etatheta.com', 'Milwaukee', 'small_scale', 'casting'),
(32, 'Theta Iota Industries', 'www.thetaiota.com', 'Albuquerque', 'medium_scale', 'coating'),
(33, 'Iota Kappa Manufacturing', 'www.iotakappa.com', 'Tucson', 'large_scale', 'moulding'),
(34, 'Kappa Lambda Enterprises', 'www.kappalambda.com', 'Fresno', 'small_scale', '3d_printing'),
(35, 'Lambda Mu Technologies', 'www.lambdamu.com', 'Sacramento', 'medium_scale', 'casting'),
(36, 'Mu Nu Manufacturing', 'www.munu.com', 'Mesa', 'large_scale', 'coating'),
(37, 'Nu Xi Works', 'www.nuxi.com', 'Kansas City', 'small_scale', 'moulding'),
(38, 'Xi Omicron Manufacturing', 'www.xiomicron.com', 'Atlanta', 'medium_scale', '3d_printing'),
(39, 'Omicron Pi Industries', 'www.omicronpi.com', 'Omaha', 'large_scale', 'casting'),
(40, 'Pi Rho Tech', 'www.piirho.com', 'Raleigh', 'small_scale', 'coating'),
(41, 'Rho Sigma Manufacturing', 'www.rhosigma.com', 'Miami', 'medium_scale', 'moulding'),
(42, 'Sigma Tau Solutions', 'www.sigmtau.com', 'Long Beach', 'large_scale', '3d_printing'),
(43, 'Tau Upsilon Fabricators', 'www.tauupsilon.com', 'Virginia Beach', 'small_scale', 'casting'),
(44, 'Upsilon Phi Industries', 'www.upsilonphi.com', 'Oakland', 'medium_scale', 'coating'),
(45, 'Phi Chi Manufacturing', 'www.phichi.com', 'Minneapolis', 'large_scale', 'moulding'),
(46, 'Chi Psi Enterprises', 'www.chipsi.com', 'Tulsa', 'small_scale', '3d_printing'),
(47, 'Psi Omega Technologies', 'www.psiomega.com', 'Arlington', 'medium_scale', 'casting'),
(48, 'Omega Alpha Manufacturing', 'www.omegaalpha.com', 'New Orleans', 'large_scale', 'coating'),
(49, 'Alpha Zeta Works', 'www.alphazeta.com', 'Wichita', 'small_scale', 'moulding'),
(50, 'Beta Eta Manufacturing', 'www.betaeta.com', 'Cleveland', 'medium_scale', '3d_printing'),
(51, 'Gamma Theta Industries', 'www.gammatheta.com', 'Tampa', 'large_scale', 'casting'),
(52, 'Delta Iota Tech', 'www.deltaiota.com', 'Bakersfield', 'small_scale', 'coating'),
(53, 'Epsilon Kappa Solutions', 'www.epsilonkappa.com', 'Aurora', 'medium_scale', 'moulding'),
(54, 'Zeta Lambda Fabricators', 'www.zetamu.com', 'Anaheim', 'large_scale', '3d_printing'),
(55, 'Eta Nu Manufacturing', 'www.etanu.com', 'Santa Ana', 'small_scale', 'casting'),
(56, 'Theta Xi Industries', 'www.thetaxi.com', 'Riverside', 'medium_scale', 'coating'),
(57, 'Iota Omicron Manufacturing', 'www.iotaomicron.com', 'Corpus Christi', 'large_scale', 'moulding'),
(58, 'Kappa Pi Enterprises', 'www.kappapi.com', 'Lexington', 'small_scale', '3d_printing'),
(59, 'Lambda Rho Technologies', 'www.lambdarho.com', 'Stockton', 'medium_scale', 'casting'),
(60, 'Mu Sigma Manufacturing', 'www.musigma.com', 'Henderson', 'large_scale', 'coating'),
(61, 'Nu Tau Works', 'www.nutau.com', 'Saint Paul', 'small_scale', 'moulding'),
(62, 'Xi Upsilon Manufacturing', 'www.xiupsilon.com', 'St. Louis', 'medium_scale', '3d_printing'),
(63, 'Omicron Phi Industries', 'www.omicronphi.com', 'Cincinnati', 'large_scale', 'casting'),
(64, 'Pi Chi Tech', 'www.pichi.com', 'Pittsburgh', 'small_scale', 'coating'),
(65, 'Rho Psi Manufacturing', 'www.rhopsi.com', 'Greensboro', 'medium_scale', 'moulding'),
(66, 'Sigma Omega Solutions', 'www.sigmaomega.com', 'Anchorage', 'large_scale', '3d_printing'),
(67, 'Tau Alpha Fabricators', 'www.taualpha.com', 'Plano', 'small_scale', 'casting'),
(68, 'Upsilon Beta Industries', 'www.upsilonbeta.com', 'Lincoln', 'medium_scale', 'coating'),
(69, 'Phi Gamma Manufacturing', 'www.phigamma.com', 'Orlando', 'large_scale', 'moulding'),
(70, 'Chi Delta Enterprises', 'www.chidelta.com', 'Irvine', 'small_scale', '3d_printing'),
(71, 'Psi Epsilon Technologies', 'www.psiepsilon.com', 'Toledo', 'medium_scale', 'casting');